### ISSUE TITLE
Linux-headers missing when installing PCIe driver [DART-MX8M-MINI Debian kernel 4.19.35].

### ISSUE THREAD

**Issue by leoniloris** [varigit/debian-var#13]
Hello,
After [building the Debian image](https://variwiki.com/index.php?title=Debian_Build_Release&release=RELEASE_BUSTER_V2.0_DART-MX8M-MINI#Build_kernel.2C_dtb_files_and_kernel_modules) I needed to install a driver for the **PCIe**  (**_gasket-dkms_**, [tutorial](https://coral.ai/docs/m2/get-started/#2a-on-linux)). But the apt complained about not having the linux-headers.

``` bash
$ apt-get install gasket-dkms
Reading package lists... Done
Building dependency tree
Reading state information... Done
Some packages could not be installed. This may mean that you have
requested an impossible situation or if you are using the unstable
distribution that some required packages have not yet been created
or been moved out of Incoming.
The following information may help to resolve the situation:

The following packages have unmet dependencies:
 gasket-dkms : Depends: linux-headers-686-pae but it is not installable or
                        linux-headers-amd64 but it is not installable or
                        linux-headers-generic but it is not installable or
                        linux-headers but it is not installable
E: Unable to correct problems, you have held broken packages.
```
__________________________________

I tried to 1) [download the kernel ](https://github.com/varigit/linux-imx/tree/imx_4.19.35_1.1.0_var01), prepare the modules and 2) build **_gasket-dkms_** from source (manually removing its dependencies):

- create linux-headers files manually:
```
git clone https://github.com/varigit/linux-imx  --branch imx_4.19.35_1.1.0_var01 && cd imx...
make O=/usr/src/linux-headers-$(uname -r) oldconfig
make O=/usr/src/linux-headers-$(uname -r) modules_prepare
```

-build and install **_gasket-dkms_**
```
git clone https://coral.googlesource.com/gasket-dkms-debian && cd gasket-dkms-debian
# - vim debian/control > Remove line #8 (dependencies)
dpkg-buildpackage -b -j10 -us -uc
cp ../gasket-dkms_1.0-13_all.deb /srv/local-apt-repository
apt clean
apt update
apt install gasket-dkms
```

But after that, the installation logs an error saying:
``` bash
Loading new gasket-1.0 DKMS files...
It is likely that 4.19.35-g7f20175d0616-dirty belongs to a chroot's host
Building for 4.19.35-g7f20175d0616-dirty
Building initial module for 4.19.35-g7f20175d0616-dirty
Error! Bad return status for module build on kernel: 4.19.35-g7f20175d0616-dirty (aarch64)
Consult /var/lib/dkms/gasket/1.0/build/make.log for more information.
dpkg: error processing package gasket-dkms (--configure):
 installed gasket-dkms package post-installation script subprocess returned error exit status 10
Errors were encountered while processing:
 gasket-dkms
E: Sub-process /usr/bin/dpkg returned an error code (1)
root@imx8mm-var-dart:~#
```
And consulting /var/lib/dkms/gasket/1.0/build/make.log:
``` bash
make[3]: *** No rule to make target '/var/lib/dkms/gasket/1.0/build/gasket_core.o', needed by '/var/lib/dkms/gasket/1.0/build/gasket.o'.  Stop.
make[3]: *** Waiting for unfinished jobs....
  LD      /var/lib/dkms/gasket/1.0/build/built-in.o
make[2]: *** [/root/imx_4.19.35_1.1.0_var01/Makefile:1490: _module_/var/lib/dkms/gasket/1.0/build] Error 2
make[1]: *** [Makefile:150: sub-make] Error 2
make: *** [Makefile:24: __sub-make] Error 2
make: Leaving directory '/usr/src/linux-headers-4.19.35-g7f20175d0616-dirty'
```

How do I install the drivers that are requiring a build with linux-headers for the PCIe (p.ex **_gasket-dkms_**)?

**Comment by leoniloris** [comment]
Up

**Comment by hj2006** [comment]
Your query has been answered on the customer portal, we will close this dependency in the upcoming Debian versions.

**Comment by leoniloris** [comment]
Thank you very much for taking the time to answer our questions.

But why aren't the questions answered using Github issues? This way, by having open questions and answers, people from different projects can enjoy answers from another projects, reducing the work for your team to eventually answer the same question multiple times.

**Comment by eranmati** [comment]
Hi @leoniloris.
Using our customer portal we can track issues much better and you will get faster answers there.
Also, it allows us to provide better support for customers who need to share private info about their products.

Regards,
Eran

**Comment by eranmati** [comment]
@leoniloris, actually we also try to answer the questions that are posted here too, but as I wrote before, the Variscite customer portal is our official place for technical questions and you will get faster answers there.
https://varisciteportal.axosoft.com/

Regards,
Eran

**Comment by hj2006** [comment]
@leoniloris : We are in the process of releasing the new Debian Bullseye with linux-headers package support in upcoming days. 
This will fix this issue and will backport the package creation from linux kernel to the filesystem.

**Comment by hj2006** [comment]
@leoniloris  The commit https://github.com/varigit/debian-var/commit/5a6ee24e48a8e53ee267d9b28c471e9d65b336b8 fixes the issue. 

Please rebuild and re-flash the OS, and run below, commands on target

echo "deb https://packages.cloud.google.com/apt coral-edgetpu-stable main" |  tee /etc/apt/sources.list.d/coral-edgetpu.list

curl https://packages.cloud.google.com/apt/doc/apt-key.gpg |  apt-key add -

apt update;apt-get install linux-headers

apt-get install gasket-dkms libedgetpu1-std

As @eranmati  suggested.  
Variscite customer portal is our official place for technical questions and you will get faster answers there.
https://varisciteportal.axosoft.com/ for all future questions.
