### ISSUE TITLE
Support for VAR-SOM-MX8M-MINI

### ISSUE THREAD

**Issue by RuhanSA079** [varigit/debian-var#17]
Hello, can you add support for the i.MX8M-Mini SOM for building a image?

I want to build a Ubuntu Core image for the i.MX8M-Mini SOM.

**Comment by RuhanSA079** [comment]
I opened this issue, thinking there is no support for the IMX8 SOM board, but I found the commit for building an u-boot image. Closing.

**Comment by eranmati** [comment]
Hi @RuhanSA079 .
Please see:
https://variwiki.com/index.php?title=VAR-SOM-MX8M-MINI

And the currently latest Debian release page for the VAR-SOM-MX8M-MINI:
https://variwiki.com/index.php?title=Debian_Build_Release&release=RELEASE_BULLSEYE_V1.0_DART-MX8M-MINI

Regards,
Eran
