### ISSUE TITLE
Customizing the rootfs

### ISSUE THREAD

**Issue by GenericWorkName** [varigit/debian-var#2]
Hello, 
Is there an option to add custom .deb packages to the rootfs? If so - how this could be done?
Is there a configuration file anywhere where additional packages can be installed?

**Comment by eranmati** [comment]
Hi generic guy.
Yes - see the protected_install function in the appropriate make_var_..._debian.sh script for your board.

Next time, please use the Variscite Customer Portal for tech support:
https://varisciteportal.axosoft.com

Regards,
Eran
