### ISSUE TITLE
Cannot build bootloader for imx8mp-var-dart Debian Bullseye

### ISSUE THREAD

**Issue by Backdraft007** [varigit/debian-var#20]
Hi,

in the repository for bullseye the folder "debian_imx8mp-var-dart/variscite/imx8mp-var-dart/imx-boot-tools" is empty. 
So the process stops at copying files.

**Comment by felixradensky** [comment]
We've pushed the missing files, sorry for the inconvenience.

**Comment by Backdraft007** [comment]
No problem Thank you.
