### ISSUE TITLE
Extra semicolon: line 802 - make_var_som_mx7_debian.sh

### ISSUE THREAD

**Issue by VAManzoEngineering** [varigit/debian-var#21]
Semicolon at the end of the following line causes error when trying to deploy source:
https://github.com/varigit/debian-var/blob/79294dca7e63122e6045df0d97005eb378f02b9a/make_var_som_mx7_debian.sh#L802

**Comment by hj2006** [comment]
@VAManzoEngineering  Thanks for reporting this. 
This issue is fixed. 
Closing this for now.
