### ISSUE TITLE
No serial TTY on UART#C_TX/RX on latest imx6ul-dart images

### ISSUE THREAD

**Issue by computermouth** [varigit/debian-var#23]
The SD card that came with my devkit booted and I was able to get a serial session on UART#C_TX/RX.

I've since built several images with the toolchain, and wrote them to the same SD card, and get no serial prompt. I tried downloading both the debian and yocto images on the FTP server, and the result is the same.

The board is booting, and I've tried UART#B and UART#A. UART#B at least shows that there's nothing wrong with my connection, as I get a spew of non-printable data. So it's not a problem with the cable or host OS or anything.

I'm using
```
cu -l /dev/ttyUSB0 -s 115200
```

So far I've only tried the latest debian and yocto builds labeled DART-6UL on the FTP server. I'll be trying the older ones as well, but could someone confirm for me that they have no issues with
```
imx6ul-var-dart-debian-bullseye-v1.0.img
dunfell-fslc-5.4-2.1.x-mx6ul-v1.1.img
```
with the im6ull and concierto board?

Also, all the board's lights are on, the heartbeat gpio led is pulsing. All signs show that the board has booted, I just don't get a tty on UART#C.

Thanks

**Comment by eranmati** [comment]
Hi @computermouth.
Please see the VAR-SOM-6UL EVK quick start guide: https://www.variscite.com/wp-content/uploads/2019/05/VAR-SOM-6UL-quick-start-guide.pdf
If you are still having issues, please open a ticket in the Variscite Customer Portal: https://varisciteportal.axosoft.com

Regards,
Eran
