### ISSUE TITLE
Build Debian root fs fails

### ISSUE THREAD

**Issue by ondrej1024** [varigit/debian-var#24]
Following the Wiki guide [VAR-SOM-MX8M-NANO - Debian Bullseye 11 with 5.4-2.1.x-imx_var01 Linux release](https://variwiki.com/index.php?title=Debian_Build_Release&release=RELEASE_BULLSEYE_5.4.142_V1.0_VAR-SOM-MX8M-NANO) I run into an issue when executing step **3.2.3 Build rootfs**:

```
sudo MACHINE=imx8mn-var-som ./var_make_debian.sh -c rootfs

...

make: Leaving directory '/home/osboxes/var_imx8mn-var-som_debian_bullseye/src/kernel'
install: cannot stat '/home/osboxes/var_imx8mn-var-som_debian_bullseye/src/freertos-variscite.build/boards/som_mx8mn/multicore_examples/rpmsg_lite_str_echo_rtos/armgcc/debug/*.elf': No such file or directory

```
Any idea how to fix this?

Thanks

**Comment by FrancescoFerraro** [comment]
Hi Ondrej, the following changes in the file variscite/imx8mn-var-som/imx8mn-var-som.sh fix the problem

readonly CM_DEMOS=" \
	multicore_examples/rpmsg_lite_str_echo_rtos \
	multicore_examples/rpmsg_lite_pingpong_rtos/linux_remote \
	demo_apps/hello_world \
	multicore_examples/rpmsg_lite_str_echo_rtos \
	multicore_examples/rpmsg_lite_pingpong_rtos/linux_remote \
	demo_apps/hello_world \
"

to

readonly CM_DEMOS=" \
	multicore_examples/rpmsg_lite_str_echo_rtos \
	multicore_examples/rpmsg_lite_pingpong_rtos/linux_remote \
	demo_apps/hello_world \
"

I'll do a general check in the debian-var repository to fix the problem
Thanks for reporting

**Comment by ondrej1024** [comment]
Thanks for the quick reply. I was just wondering why I need the FreeRTOS stuff at all for the Debian build ?

And while you are checking the repository I also came across two issues on above mentioned Wiki page:
* Step "3.2.3 Build rootfs" will fail if in step "3.2.2 Build kernel, dtb files and kernel modules" we build only `kernel` and `modules` but not `kernelheaders` which is missing from the instructions. 
* Step "3.2.4 Pack rootfs" doesn't seem to be necessary since `rootfs.tar.gz` is already created in the previous step.

Cheers

**Comment by FrancescoFerraro** [comment]
Hi Ondrej
I double checked the issue reported by you. This happens because you have to build freertos before rootfs
sudo MACHINE=imx8mn-var-som ./var_make_debian.sh -c freertosvariscite
sudo MACHINE=imx8mn-var-som ./var_make_debian.sh -c rootfs

The issue doesn't happen when you build all
sudo MACHINE=imx8mn-var-som ./var_make_debian.sh -c all |& tee build.log

The freertos demos are used by Variscite to test the M7 support

Cheers

**Comment by ondrej1024** [comment]
OK, thanks. 
Would be great if you could fix the Wiki so single step procedure works as well.

**Comment by FrancescoFerraro** [comment]
I'll take care of it ASAP
Thanks
