### ISSUE TITLE
Problem running Docker on the DART-6UL board

### ISSUE THREAD

**Issue by Vladilit** [varigit/debian-var#3]
Hi,
I have a DART-6UL SOM, and I'm having troubles when trying to install Docker on it.
I followed all of the instructions to install Debian Stretch here:
http://variwiki.com/index.php?title=Debian_Build_Release&release=RELEASE_STRETCH_V1.0_DART-6UL
And the OS seems to be working fine except when I'm trying to install Docker.

After countless attempts, I always end up with the same error - the docker service refuses to start, and the dockerd output shows: 
WARN[2018-06-03T14:35:19.454917794Z] Unable to find cpu cgroup in mounts
WARN[2018-06-03T14:35:19.456641121Z] Unable to find blkio cgroup in mounts
WARN[2018-06-03T14:35:19.458278115Z] Unable to find cpuset cgroup in mounts
WARN[2018-06-03T14:35:19.462479432Z] mountpoint for pids not found
**Error starting daemon: Devices cgroup isn't mounted**
This happens with all of the versions I tried, from docker-engine 1.12 and 1.13 to docker-ce 17 and 18

When trying "docker info" i get:
Cannot connect to the Docker daemon at unix:///var/run/docker.sock. Is the docker daemon running?

uname:
Linux imx6ul-var-dart 4.9.11-02300-ga1ac172 #1 SMP PREEMPT Tue May 29 12:31:29 IDT 2018 armv7l GNU/Linux
(I also have the same problem with the Jessie (4.1.15 kernel) version.)

Upon inspecting /sys/fs/cgroup/ I can see that all it contains is only a systemd directory.

Is there a solution?

Thanks,
Vladi

**Comment by varigigi** [comment]
Hi Vladi,
docker requires specific cgroups enabled in the kernel.
You need to enable related kernel options and rebuild a custom Debian image following the instructions here:
http://variwiki.com/index.php?title=Debian_Build_Release&release=RELEASE_STRETCH_V1.0_DART-6UL

Next time, please use the Variscite Customer Portal for tech support:
https://varisciteportal.axosoft.com

BR
Pier
