### ISSUE TITLE
set -e option no behaving correctly

### ISSUE THREAD

**Issue by AlexVndnblcke** [varigit/debian-var#4]
Hi, 

An issue appeared with the `set -e` option in the `make_var_mx6ul_dart_debian.sh`.

While creating an sdcard it appeared that if certain files were not available (e.g. rootfs.tar.gz) , the script does not exit but continues. Logically, it would seem the program would exit on error due to the `set -e`. However this is not the case. 

Seems to me the culprit is the `||` operator used while calling the functions like make_sdcard etc.

Also the exit code generated in the end is inconsistent. The sdcard couldn't be flashed so the sdcard is unusable, however it still generates an exit code of 0.  

Attached output log: for branch debian_stretch_mx6ul_var02
Command: `sudo ./make_var_mx6ul_dart_debian.sh -c sdcard -d /dev/mmcblk0`
```
...
I: Flashing U-Boot
63+0 records in
63+0 records out
64512 bytes (65 kB, 63 KiB) copied, 0.0668601 s, 965 kB/s
337+1 records in
337+1 records out
345456 bytes (345 kB, 337 KiB) copied, 0.245902 s, 1.4 MB/s
I: Flashing "BOOT-VARSOM" partition
I: Flashing "rootfs" partition
tar: /home/alexander/Documents/debian-var/output/rootfs.tar.gz: Cannot open: No such file or directory
tar: Error is not recoverable: exiting now
I: Copying Debian images to /opt/images/Debian
cp: cannot stat '/home/alexander/Documents/debian-var/output/rootfs.tar.gz': No such file or directory
I: Copying NAND U-Boot to /opt/images/Debian
I: Copying MMC U-Boot to /opt/images/Debian
I: Copying scripts to /opt/images/Debian
cp: cannot create regular file '/home/alexander/Documents/debian-var/tmp/p2/usr/sbin/': No such file or directory
cp: cannot create regular file '/home/alexander/Documents/debian-var/tmp/p2/usr/sbin/': No such file or directory
cp: cannot create regular file '/home/alexander/Documents/debian-var/tmp/p2/usr/sbin/': No such file or directory
chmod: cannot access '/home/alexander/Documents/debian-var/tmp/p2/usr/sbin/debian-emmc.sh': No such file or directory
chmod: cannot access '/home/alexander/Documents/debian-var/tmp/p2/usr/sbin/debian-nand.sh': No such file or directory
chmod: cannot access '/home/alexander/Documents/debian-var/tmp/p2/usr/sbin/kobs-ng': No such file or directory
I: Sync sdcard...
I: Done make sdcard!
I: 
I: Command: "sdcard" end. Exit code: 0
I: 
```

Kind regards
Alexander

**Comment by varigigi** [comment]
Hi Alexander,
thanks for notifying this behavior, but actually the rootfs is mandatory in order to create the SD card.
You can refer to the wiki page for the full documentation:
http://variwiki.com/index.php?title=Debian_Build_Release&release=RELEASE_STRETCH_V2.0_DART-6UL

We will evaluate possible changes to better notify script failure, but we will consider this a low priority script enhancement.

Next time, please use the Variscite Customer Portal for tech support:
https://varisciteportal.axosoft.com

Thanks
BR
Pier
