### ISSUE TITLE
Missing function in make_var_mx6ul_dart_debian.sh

### ISSUE THREAD

**Issue by iraziri** [varigit/debian-var#5]
Function install_kernel_modules is not defined in make_var_mx6ul_dart_debian.sh
Apparently the functionality of install_kernel_modules is included in function make_kernel_modules, so it's not really needed

**Comment by varigigi** [comment]
Hi,
we are currently addressing this issue and a script update will be pushed shortly.
Despite the error message this is not actually blocking the build.

Next time, please use the Variscite Customer Portal for tech support:
https://varisciteportal.axosoft.com

Thanks
BR
Pier

**Comment by varigigi** [comment]
Hi,
the problem has been fixed.
You can run "git pull" in the folder containing the debian script: you will get the updated script version.
If you need further support. please open a ticket using the Variscite Customer Portal:
https://varisciteportal.axosoft.com
Thanks
BR
Pier
