### ISSUE TITLE
use https:// instead of git://

### ISSUE THREAD

**Issue by vervaekejonathan** [varigit/debian-var#6]
The following script cannot clone the bcm_4343w_fw repository:
https://github.com/varigit/debian-var/blob/debian_stretch_mx6ul_var02/make_var_mx6ul_dart_debian.sh#L63

Due to this line:
> readonly G_BCM_FW_GIT="git://github.com/varigit/bcm_4343w_fw.git"

(probably because I have no github ssh keys configured?)

Changing this to 
> readonly G_BCM_FW_GIT="https://github.com/varigit/bcm_4343w_fw.git"

works.

**Comment by eranmati** [comment]
Hi Jonathan.
Both URLs work, however, there is no reason to use https:// in some github urls and git:// in another, so I've changed it to https as you've suggested.

Regards,
Eran

**Comment by eranmati** [comment]
Hi Jonathan.
Both URLs work, however, there is no reason to use https:// in some github urls and git:// in another, so I've changed it to https as you've suggested.

Thanks,
Eran
