### ISSUE TITLE
How about license for this repository

### ISSUE THREAD

**Issue by KunYi** [varigit/debian-var#8]
Dear,
    Would you put license description for this?
    because this repository is awesome.
    want fork the repository to modify for my project.

**Comment by andhe** [comment]
The `variscite/deb/` folder (atleast in `debian_bullseye_val01` branch) is full of modified binary debian packages without corresponding source (packages), so there seems to have been very little care for legalities/licensing...... So I'd like to extend your request with also please point out where the source can be found.

**Comment by KunYi** [comment]
I just want use tihe build script/build system to make another project.
about prebuilt debain packages should be from NXP Yocto BSP (https://source.codeaurora.org/external/imx/)
but currently I choose new build system Isar(https://github.com/ilbers/isar)
