### ISSUE TITLE
Create SD card fails when using loop device

### ISSUE THREAD

**Issue by myke239** [varigit/debian-var#9]
I am building a kernel for the Dart-6UL and ran into an issue creating firmware image without an SD card. I am building my kernel on a VM on a remote server to reduce build time, therefore, I wanted to create a .img file on the server and then copy to my local machine to flash it. 

The script var_make_debian.sh accepts a loop device as a legitimate device to write to, however, there's an issue in that the partitions are not correctly identified as loopXp1 and loopXp2, instead the script fails to write to the loop device because it appends the number to end so it is loopX1 and loopX2. 

I had to edit the format_sdcard function to add a p to so that it would format correctly

I was compiling the kernel on a headless ubuntu 18.04 server

**Comment by hj2006** [comment]
> I am building a kernel for the Dart-6UL and ran into an issue creating firmware image without an SD card. I am building my kernel on a VM on a remote server to reduce build time, therefore, I wanted to create a .img file on the server and then copy to my local machine to flash it.
> 
> The script var_make_debian.sh accepts a loop device as a legitimate device to write to, however, there's an issue in that the partitions are not correctly identified as loopXp1 and loopXp2, instead the script fails to write to the loop device because it appends the number to end so it is loopX1 and loopX2.
> 
> I had to edit the format_sdcard function to add a p to so that it would format correctly
> 
> I was compiling the kernel on a headless ubuntu 18.04 server

@myke239  thanks for your inputs, and thanks to @shlyakpavel  for his fix, we have merged the given fix to the respective branches,.

You can now refer to https://variwiki.com/index.php?title=Debian_Build_Release&release=RELEASE_BUSTER_V1.1_DART-6UL#Create_a_boot_SD_card_image_using_a_loop_device how to setup and create a new extended sdcard with loop device setup.
